version: '3.8'
services:
  postgres:
    image: postgres:16
    container_name: amanda_postgres
    restart: always
    environment:
      POSTGRES_DB: amanda_db
      POSTGRES_USER: amanda_user
      POSTGRES_PASSWORD: amanda_pass
    ports:
      - "5432:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data
volumes:
  pgdata:
